include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true # Sử dụng final cho các biến cục bộ nếu có thể
    always_declare_return_types: true # Luôn khai báo kiểu trả về cho các hàm và phương thức 
    unawaited_futures: true # Báo lỗi khi có Future không được await
    avoid_dynamic_calls: true # Uu tiên sử dụng kiểu dữ liệu cụ thể thay vì dynamic
    exhaustive_cases: true # Báo lỗi khi switch case không xử lý hết các trường hợp
    prefer_relative_imports: true # Ưu tiên sử dụng import tương đối thay vì tuyệt đối